version: '3.1'
services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: tasks
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
volumes:
  mongo-volume: